### ISSUE TITLE
[Regression] Setting time manually will not re-render

### ISSUE THREAD

**Issue by suluke** [suluke/hfg-particles#64]
Currently, while paused, the last result buffer will be drawn instead of re-running the command. I'm not sure how we want to handle this. Any suggestions, @luckyxxl ?

**Comment by suluke** [comment]
This also affects resizing it seems - when paused, the "history buffer" from accumulation is resized and reset to black it seems.

Also, what I was just thinking about: The accumulation effects are totally dependent on framerate right now, right? We should maybe try to fix this as well. Can we use different mixing factors depending on delta time?

**Comment by luckyxxl** [comment]
Did you mean this as the fix for the accumulation? I don't like that you cannot see the accumulation effect at all now if paused. Another approach: If just paused draw the last result, if seeked while paused continue to draw the particles only until play is hit again is a huge hack in my opinion.

I still suggest just rendering the accumulation effect as it is even while paused, the user should expect that such a time-based difference effect cannot be rendered correctly when paused. This simple approach yields the same results independent of whether you just paused or seeked, and you can always see that accumulation effects are active and working as expected.

**Comment by suluke** [comment]
First of all, the wording "huge hack" is not really a good basis for a constructive discussion. Please let me explain my reasoning why I think drawing only particles while paused is the better solution:
I have come to the conclusion, that rendering a frame that corresponds to a particular point in the timeline without context (i.e. a matching history buffer) is impossible when it comes to also getting the accumulation effects correctly. Therefore I don't believe that we should try to fake anything which we just cannot do right. 
What you propose has the drawback that things will continue to change after the user has paused. This seems broken to me, i.e. because it's counterintuitive/unexpected to the user in my opinion.
So what would be intuitive? Accumulation effects are essentially blur, and blur happens when things are moving. While paused, nothing is moving. Maybe it would be the most intuitive thing if we never render any accumulation effect at all while paused? On the other hand, rendering the last result on pause is also nice somehow, because it gives you the possibility to view a frame-perfect result. But I'm not completely decided on this.

I also don't think this argument from you holds true at all:
> the user should expect that such a time-based difference effect cannot be rendered correctly when paused.

**Comment by luckyxxl** [comment]
Sorry for the "huge hack", just wanted to express that I don't like that the rendering pipeline now somehow has to check the clock and do state handling for "paused", "paused but seeked" and "render normal" (and detect those state changes).

Ok, our understanding of the accumulation effects differ. While you see a "blur" effect (which could also be implemented non-time based), I explicitly see an "echo" effect, which somehow combines the last _rendered_ frames. During pause, something is rendered, too.

It is true that we can never render the "correct" frame, but I think that previewing the accumulation effect is beneficial and less confusing as a more complex logic like "you can see the current frame including accum effects, but only if you didn't seek before". It also depends whether we see out tool more as a movie editing tool (which should always lead the same results), or as a sequencing tool (which just sets parameters varying over time, yielding different results if you seek or start in the middle). The ladder is quite common for example in music, because it is also very hard/impossible to correctly render something in the middle of a track. And our "change image" and "flickr" effects already work this way, they override the default image and seeking back will not yield the same result.

**Comment by suluke** [comment]
> (which could also be implemented non-time based)

I'm talking about *motion* blur. I would be interested to see how one does it non-time-based.

> "you can see the current frame including accum effects, but only if you didn't seek before"

Different understanding here as well. As I said, this is a *feature*. which I am willing to give up if you find it too confusing.

> It also depends whether we see out tool more as a movie editing tool [...] or as a sequencing tool

I don't think this matters at all. This is just about what feels the best for the user. And in my opinion, a user wants `pause` to stop things from happening.

**Comment by luckyxxl** [comment]
Ok, so I would suggest not adding this feature :)

> I don't think this matters at all.

This is exactly what we are discussing right here. Does `pause` stop/affect _rendering_ or does it stop _sequencing_? As stated above, I always expected the latter and our "change image" effects already work this way.

**Comment by suluke** [comment]
As I said, I don't feel it's relevant to decide how we want to categorize our tool. The usability is all that matters. The user doesn't care if *sequencing* or *rendering* is stopped. All he cares about is, that stopping actually stops things from happening. The change image effects are just two examples where we fall short of achieving a movie maker, but I'm ok with that. I don't think this is a reason that we should stop trying to make it feel like a WYSIWYG editor.

I think we're at a point now where we discuss the usefulness of the seek feature. If we can't provide a "correct" (whatever that is) rendering on seek, we might as well remove it? But on the other hand, accumulation effects are so irrelevant, I would rather sacrifice those in the preview than the whole seek functionality.

**Comment by luckyxxl** [comment]
I'm the optionion that a consistent user experience is better than a "good in any case" UE. For change image effects we fall schort, but for accumulation effects we try to minimize "incorrect" results, resulting in that the tool is neither a pure sequencer nor a consistent renderer.

But I don't really care. If it's better to disable accum effects on pause (not that it makes any sense for the user in my opinion), lets do this.

> I'm talking about motion blur. I would be interested to see how one does it non-time-based.

I forgot to anwer that. Examples are screen-space per-object motion blur using motion vectors in the gbuffer, or more simple: motion blur based on camera linear velocity and/or angular velocity.
